import { GetServerSidePropsContext, InferGetServerSidePropsType } from "next";
import { getProviders, signIn } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/auth";
import Head from "next/head";
import DiscordProviderButton from "@/components/molecules/auth-provider-buttons/Discord";

export default ({ providers }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	return (
		<div>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center bg-slate-800">
				<div className="flex flex-col items-center justify-center gap-4 mt-[300px]">
          <h1 className="text-white font-bold text-4xl">Hra pro Baťu</h1>
          <p className="text-white table text-center w-[270px] md:text-md">
            Než budeš hrát, nejprve se budeš muset přihlásit
          </p>
          
          <div className="flex flex-row gap-3">
            {Object.values(providers).map((provider) => (
              <div key={provider.name}>
                <button onClick={() => signIn(provider.id)}>
                  <DiscordProviderButton/>
                </button>
              </div>
            ))}
          </div>
				</div>
			</main>
		</div>
	);
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (session) {
    return { redirect: { destination: "/game" } };
  }

  const providers = await getProviders();
  
  return {
    props: { providers: providers ?? [] },
  }
}
